### ISSUE TITLE
Remove student guide from trainer guide

### ISSUE THREAD

**Issue by rondunn** [Microsoft/MCW-SQL-Server-hybrid-cloud#10]
I suggest removing the student guide content from the trainer guide. There is a risk of difference between them, potentially leading to confusing instructions from trainer to student.

**Comment by DawnmarieDesJardins** [comment]
Thanks Ron,
The trainer guide is created, then the student guide section is copy/pasted into it’s own document so the information is exactly the same.  Having both sections in the Trainer Guide means our trainer's don't have to keep track of separate documents.
