### ISSUE TITLE
March 2019 - Scheduled content update/lab addition

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-SQL-Server-hybrid-cloud#15]
@mwasham @Jeff-Opsgility
Opsgility team -
This workshop is scheduled for an update/lab build. Please update this issue with suggested content changes. Once done, we will assign to our SME team for review and additional feedback.

**Comment by Jeff-Opsgility** [comment]
Lab would follow the existing outline in the current cloud workshop.  Deliverables of the lab would be:

•	Implementing Azure Site Recovery to replicate VMware virtual machines to Azure and orchestrate failover in the event of a disaster.
•	Using SQL Server AlwaysOn Availability Groups to provide synchronous high availability on-premises.
•	Using SQL Server AlwaysOn Availability Groups to provide asynchronous disaster recovery in Azure.
•	Take advantage of SQL Server AlwaysOn Availability Groups with readable secondaries and read-intent routing to offload the heavy read workloads.
•	Using SQL Server Always Encrypted to encrypt and decrypt PCI data at the application to protect data in-flight or at rest with keys stored in Azure Key Vault.
•	Using SQL Server Stretch Database to archive historical data to Azure SQL Database.
•	Leverage Azure Backup for centralized management and monitoring of backups.
•	Using Azure Traffic Manager with Azure Site Recovery for availability of customer-facing sites.

@DawnmarieDesJardins , please send to SME team for feedback.  Thanks.

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Hello.  Please move forward with this update and create the lab.  We'll have SMEs review the update draft when complete.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with 4/29/19 merge.
