### ISSUE TITLE
September 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-SQL-Server-hybrid-cloud#20]
This MCW is scheduled for content update.
Opsgility - please review current content and recommended updates for SME review.

**Comment by paulopsgility** [comment]
- For "Exercise 2: Implement a Data Archive Strategy with SQL Server Stretch Database", add an alternate exercise for building a partitioned table archival solution (this is a common ask/recommendation)
- Create scripts to handle failover in final exercise (in the real world you would do this with scripts to avoid human error)

**Comment by sumitsengupta** [comment]
Agreed - partitioning should be part of archival strategy.

**Comment by mokabiru** [comment]
Minor update suggestion: In the Whiteboard Design Sesion, the customer situation has reference to the following which uses the terminology **SQL Server Availability Groups**. While this is still very relevant, the official terminology we use across all our documentation is **SQL Server Always On Availiability Groups** or **Always On Availability Groups**. I think we should be consistent with our official documentation: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-2017

**Comment by paulopsgility** [comment]
Thanks everyone who provided feedback and review.
