### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by paulopsgility** [microsoft/MCW-SQL-Server-hybrid-cloud#24]
Here are our suggested updates for the June 2020 update. Please add any other suggestions or feedback to this issue.

- Update diagrams to use new Azure icons
- Update to SQL 2019
- Add Key Vault to lab
- Add Always Encrypted with Secure Enclaves

**Comment by DawnmarieDesJardins** [comment]
Add to update:
Please review and address SQL VM Resource Provider - Issue #22

**Comment by paulopsgility** [comment]
I can work in issue #22 I meant to add that anyway. Just an over site on my part.
