### ISSUE TITLE
ready for qc

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-SQL-Server-hybrid-cloud#6]

**Comment by DawnmarieDesJardins** [comment]
Thanks Michael!  Please take a look at the issue I opened and updated as needed.  Once that one is closed I'll merge, update HTML and run compliance checks.

**Comment by paulopsgility** [comment]
I closed the other issue. It should be good to go.

**Comment by DawnmarieDesJardins** [comment]
Closing issue.  September test/fix has been QC'd & merged.
