### ISSUE TITLE
WDS - student/trainer guides

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-SQL-Server-hybrid-cloud#7]
Trainer guide: **Plan for high availability and disaster recovery**.  The student guide asks 5 questions.  The 5th question is to diagram the solution.  The trainer guide does not include a diagram in the preferred solution section.  

Trainer guide:  Same as above with **Offsite backup**

**Comment by paulopsgility** [comment]
Removed these from the student guide. This has been this way for 2.5 years. Students generally just diagram the entire solution anyway.
