### ISSUE TITLE
Content review scheduled

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-SQL-Server-hybrid-cloud#9]
This workshop is scheduled for an update. Please review the contents of this repo and comment on this issue with suggested updates. All suggestions must be added to this issue by EOD November 12, 2018.

**Comment by DawnmarieDesJardins** [comment]
Adding suggestions here to close #13 issue opened 12/3.  Moving forward with update, SME review will happen after PR is ready.
  
Update diagrams for more consistency. This was logged as an issue.
Updates:
• Key management enhancement for architecture diagram etc
• Backup enhancement to use Azure Backup and a process for recovery of stretched database
• Deeper requirements/details for ASR failover scripting
• Add requirement for testing DR site (How to do this with a transactional database)

**Comment by paulopsgility** [comment]
Updates completed
